### ISSUE TITLE
English version

### ISSUE THREAD

**Issue by ANSBAFU** [hammerdirt-analyst/IQAASL-End-0f-Sampling-2021#43]
Now that the German version is the new basis I can't find the access to English version. I think it is important that the study is still available in English (and we do communicate this on the BAFU-Webpage!).

**Comment by hammerdirt-analyst** [comment]
Yes,

This needs to be added to the german version and the .pdfs.

We can do this by adding it to the footer or header of the .pdf. A link to the english version can be added to .html version right underneath the title. 

1. I just need the words in german to make the addition.
2. Verify where we put the link in both documents.

the link to the english version is [https://www.plagespropres.ch/titlepage.html](https://www.plagespropres.ch/titlepage.html)

If there are no objections to the two suggestions, all we need is the words.

It was mentioned about changing maps on the title page. I openned an issue for that:  #44 . The details of why we might want to wait a week or two are there.

**Comment by hammerdirt-analyst** [comment]
The link to the original version was added, with commit 409223a
