### ISSUE TITLE
Survey data for #EndPeriodPlastic campaign

### ISSUE THREAD

**Issue by hammerdirt-fieldops** [hammerdirt-analyst/IQAASL-End-0f-Sampling-2021#7]
Data query for the locations (nation wide), quantities, fail rate and include open date range to capture all data for G96 and G144.

**Comment by hammerdirt-analyst** [comment]
Will do

**Comment by hammerdirt-fieldops** [comment]
Please include total quantities and dimensional data, length, area, and total time.

**Comment by hammerdirt-analyst** [comment]
All done but the dims data. Will re-open issue in new repo here: https://github.com/hammerdirt-analyst/fhgproducts

**Comment by hammerdirt-analyst** [comment]
This will be handled spearately
