### ISSUE TITLE
Issue on page /esummary.html

### ISSUE THREAD

**Issue by hammerdirt-fieldops** [hammerdirt-analyst/IQAASL-End-0f-Sampling-2021#8]
Recommendations section (esummary), Add citation: _For example, single-use plastic plates, cutlery, straws, balloon sticks and cotton buds cannot be placed on the markets of the EU Member States, effective 3 July 2021._  
https://ec.europa.eu/environment/topics/plastics/single-use-plastics/eu-restrictions-certain-single-use-plastics_en

**Comment by hammerdirt-analyst** [comment]
This is a modification to the .bib file and esummary. Please make the changes and submit a pull request.
