### ISSUE TITLE
Issue on page /titlepage.html

### ISSUE THREAD

**Issue by hammerdirt-fieldops** [hammerdirt-analyst/IQAASL-End-0f-Sampling-2021#9]
Remove Native Speakers GMBH from title page

**Comment by guranshdeol** [comment]
Hi i have removed native speakers gmbh from title page kindly accept my pull request
>thanks

**Comment by hammerdirt-analyst** [comment]
Hi,

Text edits are not handled through "issues". There are too many conflicts generated. Text edits or content edits are handled by the maintainer.
